// Fortune cookies for `fortune` and ctx.fortune in user programs.
// Copied from ../api/src/lib/fortunes.ts, itself copied from the web client's public/fortune/fortunes.json.
// cIRC and C-Mail /fortune draw from the API copy on the server, so keep all three in sync.

export const FORTUNES: readonly string[] = [
  "You will be forgiven for something you forgot you did.",
  "Someone is describing you to a friend right now. You'd be surprised which detail they chose.",
  "The advice you give others is the advice you need. You noticed.",
  "Discipline and self-care can wear the same costume. You know the difference.",
  "Someone appreciates exactly the thing you take for granted.",
  "Your backup plan might be your actual plan.",
  "The closure you're chasing is already behind you.",
  "Your silence was misread as wisdom.",
  "Forgiveness is not agreement.",
  "You're almost ready to want what you actually want.",
  "Your intuition was correct. Your timing was not.",
  "The conversation that changed you is one you get to learn from.",
  "You're not behind. There is no schedule.",
  "The thing you think makes you weird is the thing they'll remember fondly.",
  "The lesson comes first. The understanding comes later. Much later.",
  "The version of you that's here now is the one that matters.",
  "Rest is not the reward. Rest is the work.",
  "Your secret is less interesting than you think. This is freedom.",
  "The closure you need can come from within. Convenient, actually.",
  "Someone actually understands you. They're closer than you think.",
  "Your comfort zone has terrible interior design.",
  "Certainty is a feeling, not a fact.",
  "The hard conversation is shorter than you think.",
  "The insight you need is in the book you abandoned on page 40.",
  "The compliment you deflected was accurate.",
  "The next moment is also a perfect moment. They keep arriving.",
  "You know what you have to do. The fortune cookie is stalling.",
  "Someone will quote you without credit. You said something worth stealing.",
  "The emotion you're holding deserves a safe place to land.",
  "Your reputation is a rumour you can't control. Relax.",
  "The door you closed quietly was braver than the one you slammed.",
  "The person you need to forgive is not who you expected.",
  "You're three honest conversations away from a different life.",
  "The version of events you rehearse is not the version that happened.",
  "Your potential is not a deadline. It's an invitation.",
  "The help you need is available. You haven't asked.",
  "Your nostalgia is editing the footage.",
  "The small thing is the big thing. It always was.",
  "The answer changes when the question matures.",
  "Someone admires your chaos.",
  "Your taste exceeds your ability. This is how growth feels.",
  "The sunk cost is already sunk. Stop diving.",
  "You're not stuck. You're resting between decisions.",
  "The chapter you're in reads better than you think from the outside.",
  "The feedback that resonates is the one worth keeping.",
  "You'll laugh about this. Not soon, but eventually.",
  "The thing you're nurturing is growing in ways you can't yet see.",
  "Someone will understand you perfectly and choose to stay. Both things happen.",
  "The permission you're seeking can only come from you. Annoying.",
  "The relationship survived what you thought would end it.",
  "Your plan B is someone's dream. Perspective.",
  "The part of you that resists is also trying to protect you. Thank it, then proceed.",
  "You're more forgiven than you feel.",
  "Someone is about to exceed your expectations. It might be you.",
  "The change happened while you were looking elsewhere.",
  "Someone needs your permission to move on. Give it.",
  "A part of you has something to say. It's worth listening to.",
  "The yes you're hoping for requires a no you haven't given.",
  "The meaning arrives after the experience. Sometimes years after.",
  "Someone just thought of you fondly. You'll never know.",
  "Your edge is also your gift.",
  "The answer you rejected was correct. Revisit it.",
  "Someone's opinion of you is about them. Even the good opinions.",
  "Your track record for getting through difficult days is perfect so far.",
  "The growth is invisible until it's undeniable.",
  "Your next chapter requires a character you haven't met yet. It's you.",
  "The kindness you extend to others is available to you. Terms and conditions apply.",
  "Your definitions are due for an update.",
  "You're fluent in a language someone needs. Speak.",
  "Your certainty about the past is also a story.",
  "Someone is waiting for you to go first.",
  "Your experience is your curriculum.",
  "The thing you're chasing is closer than it appears.",
  "You already have the answer. You're shopping for permission.",
  "Someone else's success is not your failure. Basic maths.",
  "Your future has better taste than your anxiety gives it credit for.",
  "The thing you notice in others often teaches you something about yourself.",
  "You're one question away from a different conversation.",
  "Someone took your advice. It worked. They forgot to tell you.",
  "The resistance is information. So is the longing.",
  "Your reputation preceded you. It was exaggerated. In your favour.",
  "The worst they can say is no. The worst you can do is not ask.",
  "You've already changed. Inform your self-image.",
  "Someone needs your specific kind of strange.",
  "The pattern you see in others is the pattern you know.",
  "Someone misses who you were. You don't have to.",
  "Your taste in people is improving. Progress looks good on you.",
  "Someone thinks you have it figured out. Let them.",
  "The next version of you is not a correction. It's an addition.",
  "You've been underestimating the obvious solution.",
  "Someone learned kindness from you. They won't say so.",
  "The delay is not the denial. Sometimes.",
  "Your complexity is not a burden. It's the whole point.",
  "The things you do when no one is watching are who you are.",
  "You're closer than the evidence suggests.",
  "The life you're living is someone's answered prayer.",
  "Your attention is a resource. Audit the spending.",
  "The hard thing gets easier. You're getting better at hard things.",
  "You've confused the container for the contents.",
  "Someone is about to say the thing you needed to hear.",
  "You already know what 'enough' feels like. You've talked yourself out of it.",
  "The way you receive love is allowed to have preferences. Name one.",
  "The clarity arrives after the decision. Inconvenient design.",
  "Your capacity for joy is larger than you've tested. Same muscle.",
  "Someone remembers a version of you that was perfect for them. Let it go.",
  "The person you're becoming has already started.",
  "Letting go is lighter than you expect.",
  "You're preparing for a conversation that will go better than you think.",
  "Someone is using you as a good example. You'd be surprised who.",
  "The obvious solution embarrasses you. Do it anyway.",
  "Someone saw through you completely. They stayed.",
  "The peace you keep is worth more than the argument you could win.",
  "The waiting is the thing. The present is where you live.",
  "Someone needs less of your advice and more of your presence.",
  "The part you're hiding is the part they'd like best.",
  "Someone is about to make your day. You almost missed them.",
  "Your hunger is pointing somewhere. Follow it.",
  "The thing you finished taught you more than the thing you perfected.",
  "Someone is trying to give you something. Stop deflecting.",
  "The rest of your life started several minutes ago.",
  "Someone decided you were worth the trouble. They were right.",
  "The lesson you're teaching is not the lesson they're learning.",
  "The person you actually are is ready to show up.",
  "Someone noticed your effort. They didn't say anything. It still counted.",
  "Someone's energy toward you reflects their world, not your worth.",
  "The future is not a reward for the present. It's a continuation.",
  "The version of you that said yes to this is still in there somewhere.",
  "Someone thinks about you at odd moments. Traffic. Grocery stores.",
  "Your definition of success was inherited. Question the source.",
  "Someone else's path looks simpler because you can't see their obstacles.",
  "The apology you owe is smaller than the one you're preparing.",
  "Your need to be understood is getting in the way of being known.",
  "The change you want is making space for itself.",
  "Someone learned their limits by watching you exceed yours.",
  "The question is not whether you can. The question is whether you will.",
  "The next chapter begins before you finish naming it.",
  "Someone is proud of you for the thing you dismiss.",
  "Someone believes the version of you that you performed once.",
  "Your comfort is someone else's goal. Perspective shifts both ways.",
  "The choice you think is permanent rarely is.",
  "Someone is waiting for you to take up the space you deserve.",
  "The clarity you want is on the other side of action, not before it.",
  "The parts of you that don't fit are not errors.",
  "You're safer now than your nervous system believes. Update it gently.",
  "The answer changes when you're honest about the question.",
  "Someone needs you to go second. Wait for them.",
  "Your desire for connection is a signal worth following.",
  "Someone else carries a version of you they never update.",
  "Someone understood you completely for thirty seconds. It was enough.",
  "The emotion you acknowledge finds healthy exits.",
  "The thing you're loyal to appreciates you more than you know.",
  "The love that's available confuses you because it's not difficult.",
  "Someone is still thinking about that thing you said. The kind thing.",
  "The self you are is easier to maintain than you think.",
  "Your idealism is still in there. It's just resting.",
  "The goal you reached doesn't feel how you expected. Normal.",
  "Someone learned generosity by watching you share yours.",
  "The moment you're in is unrepeatable. Notice something.",
  "Someone respects you more than they like you. That's worth something.",
  "The thing you're building in the dark will be seen eventually.",
  "Your ability to adapt is a strength. So is choosing calm.",
  "Someone is about to ask for help.",
  "The pattern you're in has an exit.",
  "The thing you mastered once was once impossible.",
  "Someone else's certainty is not your evidence.",
  "The opportunity is disguised as work. As usual.",
  "Someone is grateful for you specifically. Not a generic you.",
  "Someone noticed your absence. They didn't mention it.",
  "The simplification you resist is the simplification you need.",
  "Your opinions about yourself are not facts.",
  "Someone is rooting for you from a distance. Unknown cheering section.",
  "The love you give yourself has a way of spreading.",
  "Your plateau is preparation. Probably.",
  "Someone learned how to treat people by watching how you treated them.",
  "Your desire to be unique and your desire to belong can coexist.",
  "The thing you share becomes the thing that connects you.",
  "Someone is trying to return something you left behind.",
  "Your presence is the present. Sorry for the pun. It's still true.",
  "The quality you admire most in others also lives in you.",
  "Someone is cheering for your success.",
  "The courage you need arrives during, not before.",
  "Your solitude can be restorative. You decide the dose.",
  "Someone trusted you with their truth. Handle it gently.",
  "Your memory of the event and the event have diverged.",
  "The rest of them are also pretending to know what they're doing.",
  "Someone is narrating their life, and you're a minor character. Relief.",
  "The choice you made with incomplete information was still the right call.",
  "The freedom you're seeking has already been granted. By you.",
  "Someone remembers your kindness more than your competence.",
  "The person in the mirror has been patient. They're ready when you are.",
  "Your need to explain yourself is optional.",
  "The lesson arrives on time. Your readiness varies.",
  "The path forks again. It always does.",
  "The reward was the process. The results are a bonus.",
  "Your loyalty is admirable when it's mutual.",
  "Someone just decided you're worth knowing better.",
  "Your capacity to change exceeds your belief in it.",
  "The easy thing and the right thing overlapped this once. Enjoy it.",
  "Someone needs your wrong answer. It helps them find their right one.",
  "The silence between you is not empty.",
  "The good thing approaching doesn't announce itself. It just arrives.",
  "Someone just thought of you and smiled.",
  "Someone out there has the exact puzzle piece you're missing. You'll meet soon.",
  "Your random act of kindness last week is still rippling.",
  "The playlist you made is someone's favourite.",
  "You're about to have a really good snack. You deserve it.",
  "Someone is going to laugh at your joke harder than you expect.",
  "The book you'll love most hasn't found you yet. It's on its way.",
  "Your handwriting is more charming than you think.",
  "The song stuck in your head is preparing you for something.",
  "Someone saved a message you sent them.",
  "You're one sunset away from a new perspective.",
  "The universe keeps a highlight reel of your best moments.",
  "Your enthusiasm is contagious in the best way.",
  "Someone just used a word they learned from you.",
  "The nap you're considering is medically advisable.",
  "Your favourite season is coming back around.",
  "Someone thinks your laugh is the best sound.",
  "The next meal you cook will turn out better than expected.",
  "You're someone's example of how to do it right.",
  "The plant you forgot to water is more resilient than you think.",
  "Your future self just sent a thank you note. It's in the mail.",
  "Someone is about to recommend something you'll love.",
  "The thing you almost said out loud? Say it.",
  "You're accumulating good karma faster than you realise.",
  "The stranger who smiled at you meant it.",
  "Your comfort movie knows exactly what you need.",
  "Someone is telling a story about you right now, and you're the hero.",
  "The compliment you're about to receive is 100% sincere.",
  "Your internet rabbit hole tonight will teach you something useful.",
  "The friend you haven't talked to in a while thinks about you often.",
  "You're about to find something you thought you'd lost.",
  "Someone copied your style. Take it as the compliment it is.",
  "The creative thing you made? Someone treasures it.",
  "You're someone's proof that good people exist.",
  "The coffee tomorrow will be perfectly brewed.",
  "Someone admires how you handle things.",
  "Your gut feeling is smarter than you give it credit for.",
  "The conversation you're dreading will be surprisingly easy.",
  "You've made more people's days than you'll ever know.",
  "The outfit you're unsure about? It works.",
  "Someone just defended you in a conversation you weren't part of.",
  "The thing you're learning will come in handy sooner than expected.",
  "You're someone's favourite notification.",
  "The idea you had in the shower was actually brilliant.",
  "The dishes can wait. Life cannot!",
  "Do it on the next full moon.",
  "It will take less than twenty minutes.",
  "Your overthinking has accidentally produced wisdom.",
  "The thing you're procrastinating on takes twelve minutes. Tops.",
  "Someone described you to a stranger. It was flattering.",
  "The walk you're putting off will solve two problems at once.",
  "Your instinct to pause was the right call. Again.",
  "The recipe you improvised is now canon.",
  "Your old self would be impressed by your current self. Allow it.",
  "Someone trusted your recommendation. It landed.",
  "The stretch you need is the one you keep skipping.",
  "Your next deep breath will be unreasonably satisfying.",
  "Someone quoted you at dinner. You weren't there.",
  "Your sense of direction is better than your confidence in it.",
  "The thing you're avoiding is smaller up close.",
  "Someone learned patience by watching yours.",
  "The cup of tea you're about to make is the correct decision.",
  "Your capacity for wonder is intact.",
  "The door you almost didn't knock on opens easily.",
  "Someone carries a sentence you said like a lucky coin.",
  "Your stubbornness and your dedication are the same trait. Context matters.",
  "The meal you share tonight matters more than the menu.",
  "Someone is braver today because of something you said last year.",
  "Your sense of humour has saved more situations than your logic.",
  "The garden grows while you sleep. Some things don't need supervision.",
  "Someone forgave you without telling you. The debt is clear.",
  "The place that feels like home is not always a place.",
  "Your questions are more interesting than most people's answers.",
  "Someone still laughs about a thing you did. The good kind.",
  "The habit you're building is already building you back.",
  "Your handwriting tells a story you never meant to share.",
  "The stranger who held the door felt your gratitude. It mattered.",
  "Someone is saving a seat for you. Figuratively. Maybe literally.",
  "Your ability to find beauty in ordinary things is a rare currency.",
  "The apology you rehearsed can be three words. That's enough.",
  "Someone learned generosity from your example. No lecture required.",
  "Your favourite weather is forecast for this week.",
  "The conversation you've been replaying already had its ending. Let the credits roll.",
  "Someone is about to agree with you and mean it.",
  "Your unfinished projects know where to find you. They're patient.",
  "The kindness you chose when it was inconvenient defined you.",
  "Someone you admire also admires you. Neither of you has mentioned it.",
  "Your collection of small joys is more valuable than you've appraised.",
  "The best decision you ever made looked reckless at the time.",
  "Someone finds your company restful. Not boring. Restful.",
  "The thing you've been circling is ready for you to land.",
  "Your laughter has echoed in rooms you've already left.",
  "Someone kept the thing you gave them. It's on a shelf.",
  "The ordinary morning you're having might be the one you remember fondly.",
  "Your instinct to be kind when you could be clever is the right one.",
  "The view from the other side of this is worth the walk.",
  "The shortcut you're avoiding is actually the long way around.",
  "Your ability to sit with uncomfortable silence is an underrated flex.",
  "The thing you did on impulse was the most honest thing you did all week.",
  "You are one well-timed compliment away from making someone's whole month.",
  "The draft you almost deleted is better than the final version you agonised over.",
  "Your attention span is fine. The thing was just boring.",
  "The friendship that survives long gaps is the real infrastructure.",
  "You've been rehearsing a speech for an audience that already agrees with you.",
  "The boundary you set last time is still holding. Good fence.",
  "Your ability to function while uncertain is wildly impressive. You don't see it.",
  "The habit you dropped without noticing was the one that needed to go.",
  "You confused being needed with being valued. Different currencies.",
  "The thing you keep apologising for wasn't that serious. Everyone moved on except you.",
  "Your worst-case scenario has a terrible imagination. Real life is more creative.",
  "The meal you ate standing over the sink still counted as self-care. Barely.",
  "You know more than you can articulate. That's called wisdom, not confusion.",
  "The person you pretend to be in interviews is closer to the real you than you admit.",
  "Your browser tabs are a portrait of your curiosity. Frame it.",
  "The errand you've been postponing will take eleven minutes. Twelve, tops.",
  "You are not your most embarrassing Google search. Probably.",
  "The text you overthought for twenty minutes landed perfectly. As always.",
  "Your ability to laugh at yourself is doing more heavy lifting than your résumé.",
  "The argument you won in the shower was very persuasive.",
  "You don't need a sign from the universe. You need a glass of water and ten minutes.",
  "The thing you built with no plan has more character than the thing you planned perfectly.",
  "Your half-finished projects are not failures. They're a research phase with no deadline.",
  "The dog that looked at you today saw your entire soul and approved.",
  "You are fluent in a dialect of kindness that some people have never encountered.",
  "The nap is not laziness. The nap is strategy.",
  "Your refrigerator believes in you. Go see what it's got.",
  "The panic was useful for about four seconds. The rest was theatre.",
  "You've been training for this your whole life. The training was disguised as chaos.",
  "The thing you call a flaw is the thing that makes your stories interesting.",
  "Your handwriting gets worse when you're onto something good.",
  "The email you're dreading has already been answered in your head. Just type it.",
  "You are three deep breaths and one good question away from a breakthrough.",
  "The song you can't stop humming is trying to tell you something. Or it's just catchy.",
  "Your relationship with your bed is the most stable one in your life. Cherish it.",
  "The uncomfortable truth is smaller than the comfortable lie. Always.",
  "You have been someone's unexpected highlight more times than you will ever know.",
  "The list you made at 3am was actually quite sensible. Check it again.",
  "Your tolerance for nonsense has decreased. This is called growth.",
  "The snack you're debating is already approved. Go.",
  "You're not overthinking. You're pre-processing. Totally different.",
  "The compliment you gave a stranger last month is still in circulation.",
  "Your instinct to rest is as valid as your instinct to push. Alternate accordingly.",
  "The version of you that shows up tired and tries anyway is the most impressive one.",
  "You are held in higher regard by your houseplants than you deserve.",
  "The thing you keep putting off is afraid of you too. Go introduce yourself.",
  "The algorithm doesn't know you. Your friends do. Call one.",
  "Your ability to make something out of nothing is called creativity. Also Tuesday.",
  "The plan fell apart. The outcome didn't. You improvised better than you think.",
  "You are someone's proof that the internet isn't all bad.",
  "The thing you almost bought at 2am would not have fixed it.",
  "Your socks don't match. Nobody cares. This applies to most things.",
  "The muscle you're building right now is patience. Awful exercise. Worth it.",
  "You have outlasted every bad mood you've ever had. Undefeated.",
  "The book on your nightstand is judging you gently. Open it or set it free.",
  "Your ability to find the funny in the terrible is a survival skill with excellent reviews.",
  "The meeting that could have been an email was not your fault.",
  "You've given better advice to strangers than you give yourself. Redirect.",
  "The Wi-Fi going out was the universe's way of saying go outside. Or fix the router. Both valid.",
  "Your skeleton has been carrying you without a single complaint. Respect.",
  "The thing that scared you last year is something you'd handle easily now.",
  "You are not too much. You are the right amount in the wrong room.",
  "The leftovers in your fridge are a love letter from yesterday's you.",
  "Your ability to start over on a Wednesday is heroic and underappreciated.",
  "The typo you sent was funnier than what you meant to say.",
  "You've survived every plot twist so far. Your track record is flawless.",
  "The thing you think everyone noticed, nobody noticed. You're free.",
  "Your indoor voice has outdoor wisdom. Let it out occasionally.",
  "The goodbye you didn't get was not the one you needed anyway.",
  "You are one good playlist away from solving at least two problems.",
  "The cat that ignored you was actually deeply impressed. That's just how they show it.",
  "Your capacity to care about small things is not small. It's precise.",
  "The decision you made hungry was still defensible. Mostly.",
  "You have been brave in rooms that didn't notice. The bravery still counted.",
  "The question you were too embarrassed to ask has ten million search results. You're in good company.",
  "Your laugh sounds exactly right. Stop editing it.",
  "The homework you did on yourself is paying compound interest.",
  "You've been someone's calm in a storm and didn't even know it was raining.",
  "The walk you took instead of replying was the correct response.",
  "Your ability to keep a secret is more valued than you realise.",
  "The thing you fixed with tape and optimism is still holding. Engineer.",
  "You are one honest conversation away from lighter shoulders.",
  "The sunset doesn't care if you photograph it. It showed up for you anyway.",
  "Your old journals would be proud of your current handwriting. And your current life.",
  "The person you were kind to in passing remembers it in detail.",
  "You have been the right person at the right time more than statistics would predict.",
  "The hobby you abandoned still taught you something. Tuition was reasonable.",
  "Your sense of direction works fine. You just live somewhere confusing.",
  "The fear of being ordinary is itself very ordinary. Welcome to the club.",
  "You made the complicated thing look easy. Someone learned from that.",
  "The tea has gone cold. This is not a metaphor. Go reheat it.",
  "Your definition of a good day is more achievable than you've set it.",
  "The thing holding you back weighs less than you think. Put it down and check.",
  "You are the plot twist in someone's otherwise predictable week.",
  "The stars aligned while you weren't looking. They do that.",
  "Your next good idea is disguised as a shower thought. Pay attention in there.",
  "A bird you have never met knows your schedule. It approves.",
  "The third drawer from the top contains a secret you forgot to put there.",
  "You will soon be near a very small door. It is not for you, but wave anyway.",
  "The number seven is rooting for you. The number four is neutral. The number twelve is complicated.",
  "An elevator in a building you don't work in is thinking of you fondly.",
  "You once dreamed of a hallway. That hallway still exists. It's fine.",
  "The moon owes you one favour. Cash it in on a Wednesday.",
  "A librarian somewhere is re-shelving a book you'll need in three years.",
  "You will encounter a single sock with opinions. Respect them.",
  "The vending machine remembers what you almost picked last time. It's not mad.",
  "Somewhere in the world, a potato is in the exact shape of your good mood.",
  "The wind is carrying a rumor about you. It's flattering and largely untrue.",
  "A stranger's umbrella once saved your haircut without anyone noticing.",
  "You are owed a refund by a cloud. Claim it verbally, facing north.",
  "The correct password is a feeling you had in 2011.",
  "Beneath your left shoe, for just one second today, there will be an ant of unusual talent.",
  "A map you didn't draw leads to a snack you already own.",
  "The hum of your fridge is composing a symphony. Third movement is next week.",
  "Your reflection has been practicing a small wave. It may debut without warning.",
  "There is a perfect pebble within fifty meters of you. It is waiting to be noticed, not picked up.",
  "You will one day open a jar on the first try and nobody will be watching. It still counts.",
  "A forgotten tab in your browser is quietly achieving enlightenment.",
  "The ceiling above you is doing an excellent job. Thank it mentally.",
  "A small animal in a faraway country has a name that rhymes with yours. This is meaningful in their language.",
  "Your keys are where you last had hope. Think about that and go look.",
  "The color teal is going to try something. Let it.",
  "You will soon say the phrase 'that's oddly specific' and mean it.",
  "Somewhere a kettle is whistling the exact note you needed to hear.",
  "A houseplant two streets away thinks you are doing great.",
  "The staircase is counting you. It has reached a number it likes.",
  "You will find a coin from a country you've never visited. Do not spend it. Do not explain it.",
  "The soup remembers. The soup forgives. The soup moves on.",
  "A cat you have never met has already decided you are okay.",
  "Your shadow has been practicing a new pose. Catch it in a window this week.",
  "The correct answer is seventeen. The question has not been asked yet.",
  "A door you walked past today was almost the right one. The universe is very polite about these things.",
  "You will briefly lock eyes with a pigeon that knows more than it lets on.",
  "The back of your knee has never let you down. Consider this.",
  "A song you haven't heard in years is waiting in the next grocery store you enter.",
  "The letter 'Q' is feeling underused. Work it in somewhere this week.",
  "There is a staircase in your future with one extra step. You will adjust beautifully.",
  "A squirrel has buried a nut in your honor. It will not remember. The gesture counts.",
  "You will hear a word you haven't thought about since childhood. It will bring snacks.",
  "The time on a broken clock you pass this week will be accidentally meaningful.",
  "A raindrop is reserved for the top of your head. Delivery window: soon.",
  "The correct number of spoons in a drawer is whatever you currently have, plus one.",
  "You will smell bread you did not bake. This is a gift from a stranger you'll never meet.",
  "A paper airplane thrown in 1997 is still, technically, on its way.",
  "The bench you sit on next is holding a story for you. You won't know. The bench will.",
  "Your left pocket is slightly luckier than your right. Rotate accordingly.",
  "A bee once considered landing on you and chose dignity instead. You are welcome.",
  "The next time you sneeze, a small light bulb in a distant city will briefly flicker. Unrelated. Probably.",
  "The bird outside your window earlier today was you, checking in.",
  "There is a version of this that involves pineapple. Consider it.",
  "Count the yellow cars this week. Stop at seven. Then something.",
  "Someone in another time zone just laughed at a thing you said last Tuesday.",
  "The key that doesn't fit anything is for a door that hasn't been built yet.",
  "A small frog considered your life from a leaf and approved.",
  "The word \"limestone\" will matter on a Thursday.",
  "You are three decisions away from a very specific balcony.",
  "The third word you say tomorrow will echo back by Sunday.",
  "The fourth cup was the good one.",
  "A glossary in a book nobody finished has your name as an example.",
  "Twelve minutes past any hour is yours.",
  "The thing under the couch has been there for exactly the right amount of time.",
  "A door you forgot about is still pleased to have you.",
  "The ghost in the kettle is benevolent and mostly punctual.",
  "Whisper into a succulent. It keeps secrets better than a diary.",
  "Someone drew a map with your initials and gave it to a child.",
  "The second-best seat is the correct one today.",
  "A postcard addressed to you has been taking the scenic route since 1997.",
  "The stone you skipped as a kid is still skipping.",
  "A constellation in the Southern Hemisphere is arranged suspiciously like your signature.",
  "Try the other doorway.",
  "A moth read your to-do list and was impressed.",
  "You are owed one (1) small miracle. Redeemable at the next awkward pause.",
  "The number 47 is watching your back this quarter.",
  "Eat something orange to unlock Tuesday.",
  "The library of small, correct choices is adding a new wing for you.",
  "A bakery you've never entered already knows your order.",
  "The crow on the fence remembers your grandmother.",
  "Turn the page before the chapter ends. It's fine. You'll come back.",
  "The coat you never wore is still waiting for weather.",
  "A coin you lost in 2013 is now someone else's lucky charm. Even trade.",
  "The photocopier considers you a friend of the establishment.",
  "Keep left at the next metaphor.",
  "The Wi-Fi at the place you're about to go is better than advertised.",
  "A raccoon, unseen, nodded at a thing you did last night.",
  "Your houseplants keep a group chat. You are a recurring topic.",
  "The bookstore cat has opinions. Go, but don't press it.",
  "On Friday, someone will say \"oh!\" because of you.",
  "Your bicycle has been telling stories about you. They are mostly true.",
  "A leaf will land on your shoulder this week as a tap on the shoulder.",
  "The password to a forgotten account of yours is one syllable away.",
  "A pigeon in a city you've never visited ate a crumb meant for you.",
  "The tallest thing you see tomorrow is rooting for you.",
  "A glitch in the produce aisle is in your favour today.",
  "Somewhere, a printer is printing a page that will make you laugh. Be near one.",
  "The fourth ingredient is optional. The fifth is not.",
  "Your future self has already forgiven the thing you're worried about.",
  "A lighthouse operator dreamt of your name last night, spelled slightly wrong.",
  "The universe has filed your request under \"soon, and with style\".",
  "The one who knocks is wearing the door's coat.",
  "What you are practicing has already learned your name.",
  "The answer you can carry in one hand is the wrong size.",
  "To find it, become uninteresting to the search.",
  "What is given freely arrives in a language you almost remember.",
  "The name and the named pass each other without looking up.",
  "You arrive by forgetting the shape of the going.",
  "What knows you has been waiting in the next room the whole time.",
  "The silence between two words has a colour. You have seen it.",
  "To be understood, stop translating, and let the accent do the work.",
  "The question you are asking is wearing the costume of the answer.",
  "What is yours will recognise you even if you arrive in disguise.",
  "The path narrows where the walker widens.",
  "To be heard, lower your voice past where listening begins.",
  "What you cannot name is keeping your seat warm.",
  "The teacher has been in your sentence for years, posing as punctuation.",
  "To know it, let it be slightly wrong about you.",
  "The hand that opens is the hand that was being filled.",
  "What is true twice is rarely true a third time.",
  "The breath you are holding has somewhere to be.",
  "To rest, stop offering the silence a job.",
  "The seeker has the same handwriting as the hidden.",
  "What returns to you was never required to leave.",
  "The student arrives the moment the question stops being polite.",
  "The wind learns its direction from the leaves, not the other way.",
  "What you almost said has already done its work.",
  "The smaller key fits the larger door.",
  "Stop bargaining with the echo.",
  "The instrument tunes itself by being played badly first.",
  "What is hidden is rehearsing for the moment you look elsewhere.",
  "The shadow keeps better time than the clock.",
  "The lock remembers the key that almost worked.",
  "What you carry without noticing is what is carrying you.",
  "The room you walk past three times a day knows your gait.",
  "To remember, ask the air what you said.",
  "What is given by the giver does not always reach the gift.",
  "The lamp is not the light. The light is busy.",
  "To know yourself, ask what you avoid being thanked for.",
  "The third time you forget it, it is no longer forgetting.",
  "What you mistake for noise is sometimes a name.",
  "The smallest door in the house leads everywhere.",
  "To proceed, let the path forget you for a moment.",
  "What you are afraid to want has already filled out the paperwork.",
  "The opposite of certainty is not doubt. It is roominess.",
  "To grow it, stop checking. Watered things resent being measured.",
  "The bell does not know it is ringing. This is why it can.",
  "What waits patiently is often wearing your shoes.",
  "To enter, agree to be slightly the wrong size.",
  "What you cannot give away is borrowing you.",
  "The threshold remembers everyone, in alphabetical order.",
  "To find the thread, lose the spool.",
  "The unspoken is heavier than the unsaid. Different muscles.",
  "What stays close is not always loyal. Sometimes it is curious.",
  "The teacher in the room is not necessarily standing.",
  "To listen to it, let it mispronounce your name first.",
  "The borrowed light is still light.",
  "What you cannot finish is keeping the door open for you.",
  "The watcher cannot be watched, but it answers when properly addressed.",
  "To be at home, stop redecorating the doorway.",
  "What knocks twice rarely meant the first time.",
  "The instruction comes through the floor when the ceiling refuses.",
  "The hidden is not hiding. It is occupied.",
  "What you postpone often postpones you in return.",
  "The first sentence of the day is reading you.",
  "To be lighter, set down what you forgot you were holding.",
  "The dictionary does not know what the word feels like.",
  "What is shared without translation arrives whole.",
  "The argument you are winning is asking for directions.",
  "To recognise it, look for what does not require introduction.",
  "The corridor remembers the door at both ends.",
  "What you have not noticed yet has already noticed you.",
  "The yes that is also a question is a better yes.",
  "To be still, give the stillness something to do.",
  "The compass needle is not pointing. It is agreeing.",
  "What surprises you twice is no longer a surprise.",
  "The half-built thing has its own kind of completion.",
  "To be honest, choose the slightly less elegant sentence.",
  "The pause has a shape. You have practised it for years.",
  "What you cannot prove sometimes proves you.",
  "The afternoon has opinions. It rarely shares them.",
  "To know the season, ask what the door does not say when it closes.",
  "The repeated word is a small door, opened twice.",
  "What you cannot picture has already drawn you.",
  "To be guided, stop correcting the guide.",
  "The doorway is wider when you do not announce yourself.",
  "What you are looking for is also keeping you company while you look.",
  "The question is not waiting for an answer. It is taking attendance.",
  "The hinge has a longer memory than the door.",
  "The keyhole is not for the key. It is for the looking.",
  "The clock is not measuring time. It is taking dictation.",
  "The stranger you keep meeting is your future arriving in installments.",
  "The shadow is not following. It is co-signing.",
  "The first thought of the morning is not yours. It is the room speaking.",
  "The corner of your eye is the part that believes you.",
  "The page knows when you are not reading. It rests."
]
